GET https://localhost:7229/minecraftserver/1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKV1RTZXJ2aWNlQWNjZXNzVG9rZW4iLCJqdGkiOiI2MTIzMThhNS05YWQ0LTQ3MzEtYjFjNi03ZTExZTBkN2I4ZGEiLCJpYXQiOiIgMjAyMi4xMS4wNyAxMDo0Njo1NyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJUZXN0ZXIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIwIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU3lzdGVtIiwiUGxhdGZvcm0iOiJEaXNjb3JkIiwiZXhwIjoxNjY4NjgyMDE3LCJpc3MiOiJKV1RBdXRoZW50aWNhdGlvblNlcnZlciIsImF1ZCI6IkpXVFNlcnZpY2VCbGF6b3JXYXNtQ2xpZW50In0.6ax5xdDStKPETk1Cr3eunPmn489n-SaH_pksABDqP55U0u9v7wE9gq85QLFwhImkhtpuq0oGTjw3_sj-7o-BnQ


###

GET http://api.positionstack.com/v1/forward?access_key=7a05b023ffaf3864eb2d6f859a946876&query=Lilli%20Gyldenkildes%20Torv%201%2C%20Horsens&country=dk